/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoasRouteImport } from './routes/roas'
import { Route as AosRouteImport } from './routes/aos'
import { Route as IndexRouteImport } from './routes/index'

const RoasRoute = RoasRouteImport.update({
  id: '/roas',
  path: '/roas',
  getParentRoute: () => rootRouteImport,
} as any)
const AosRoute = AosRouteImport.update({
  id: '/aos',
  path: '/aos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aos': typeof AosRoute
  '/roas': typeof RoasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aos': typeof AosRoute
  '/roas': typeof RoasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aos': typeof AosRoute
  '/roas': typeof RoasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aos' | '/roas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aos' | '/roas'
  id: '__root__' | '/' | '/aos' | '/roas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AosRoute: typeof AosRoute
  RoasRoute: typeof RoasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roas': {
      id: '/roas'
      path: '/roas'
      fullPath: '/roas'
      preLoaderRoute: typeof RoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos': {
      id: '/aos'
      path: '/aos'
      fullPath: '/aos'
      preLoaderRoute: typeof AosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AosRoute: AosRoute,
  RoasRoute: RoasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
