/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YasirVipRouteImport } from './routes/yasir-vip'
import { Route as RoasRouteImport } from './routes/roas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YasirIndexRouteImport } from './routes/yasir/index'
import { Route as AosIndexRouteImport } from './routes/aos/index'
import { Route as YasirPageRouteImport } from './routes/yasir/$page'
import { Route as AosPageRouteImport } from './routes/aos/$page'
import { Route as AosV1PageRouteImport } from './routes/aos-v1/$page'

const YasirVipRoute = YasirVipRouteImport.update({
  id: '/yasir-vip',
  path: '/yasir-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const RoasRoute = RoasRouteImport.update({
  id: '/roas',
  path: '/roas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YasirIndexRoute = YasirIndexRouteImport.update({
  id: '/yasir/',
  path: '/yasir/',
  getParentRoute: () => rootRouteImport,
} as any)
const AosIndexRoute = AosIndexRouteImport.update({
  id: '/aos/',
  path: '/aos/',
  getParentRoute: () => rootRouteImport,
} as any)
const YasirPageRoute = YasirPageRouteImport.update({
  id: '/yasir/$page',
  path: '/yasir/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AosPageRoute = AosPageRouteImport.update({
  id: '/aos/$page',
  path: '/aos/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AosV1PageRoute = AosV1PageRouteImport.update({
  id: '/aos-v1/$page',
  path: '/aos-v1/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roas': typeof RoasRoute
  '/yasir-vip': typeof YasirVipRoute
  '/aos-v1/$page': typeof AosV1PageRoute
  '/aos/$page': typeof AosPageRoute
  '/yasir/$page': typeof YasirPageRoute
  '/aos/': typeof AosIndexRoute
  '/yasir/': typeof YasirIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roas': typeof RoasRoute
  '/yasir-vip': typeof YasirVipRoute
  '/aos-v1/$page': typeof AosV1PageRoute
  '/aos/$page': typeof AosPageRoute
  '/yasir/$page': typeof YasirPageRoute
  '/aos': typeof AosIndexRoute
  '/yasir': typeof YasirIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roas': typeof RoasRoute
  '/yasir-vip': typeof YasirVipRoute
  '/aos-v1/$page': typeof AosV1PageRoute
  '/aos/$page': typeof AosPageRoute
  '/yasir/$page': typeof YasirPageRoute
  '/aos/': typeof AosIndexRoute
  '/yasir/': typeof YasirIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/roas'
    | '/yasir-vip'
    | '/aos-v1/$page'
    | '/aos/$page'
    | '/yasir/$page'
    | '/aos/'
    | '/yasir/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/roas'
    | '/yasir-vip'
    | '/aos-v1/$page'
    | '/aos/$page'
    | '/yasir/$page'
    | '/aos'
    | '/yasir'
  id:
    | '__root__'
    | '/'
    | '/roas'
    | '/yasir-vip'
    | '/aos-v1/$page'
    | '/aos/$page'
    | '/yasir/$page'
    | '/aos/'
    | '/yasir/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoasRoute: typeof RoasRoute
  YasirVipRoute: typeof YasirVipRoute
  AosV1PageRoute: typeof AosV1PageRoute
  AosPageRoute: typeof AosPageRoute
  YasirPageRoute: typeof YasirPageRoute
  AosIndexRoute: typeof AosIndexRoute
  YasirIndexRoute: typeof YasirIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yasir-vip': {
      id: '/yasir-vip'
      path: '/yasir-vip'
      fullPath: '/yasir-vip'
      preLoaderRoute: typeof YasirVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roas': {
      id: '/roas'
      path: '/roas'
      fullPath: '/roas'
      preLoaderRoute: typeof RoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yasir/': {
      id: '/yasir/'
      path: '/yasir'
      fullPath: '/yasir/'
      preLoaderRoute: typeof YasirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/': {
      id: '/aos/'
      path: '/aos'
      fullPath: '/aos/'
      preLoaderRoute: typeof AosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yasir/$page': {
      id: '/yasir/$page'
      path: '/yasir/$page'
      fullPath: '/yasir/$page'
      preLoaderRoute: typeof YasirPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/$page': {
      id: '/aos/$page'
      path: '/aos/$page'
      fullPath: '/aos/$page'
      preLoaderRoute: typeof AosPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos-v1/$page': {
      id: '/aos-v1/$page'
      path: '/aos-v1/$page'
      fullPath: '/aos-v1/$page'
      preLoaderRoute: typeof AosV1PageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoasRoute: RoasRoute,
  YasirVipRoute: YasirVipRoute,
  AosV1PageRoute: AosV1PageRoute,
  AosPageRoute: AosPageRoute,
  YasirPageRoute: YasirPageRoute,
  AosIndexRoute: AosIndexRoute,
  YasirIndexRoute: YasirIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
